### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by jnk22** [valentinhofmann/flota#2]
Hi, @CeGa-byte and I would like to fork this repo and work with this code within a university project.

Unfortunately there doesn't seem to be a license included in your repo that officially allows to do so.

Would it be possible to add such a license that makes working with this code (and potentially contributing upstream as well) easier?

**Comment by valentinhofmann** [comment]
Hi @jnk22, thanks for the note and interest in our repo - I've just added a license.

**Comment by jnk22** [comment]
That is great, thank you!
